# Project: Day11
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ex16-1.o ex16-2.o ex16-3.o ex16-4.o work.o ex16-6.o ex17-1.o ex17-2.o ex17-3.o
LINKOBJ  = ex16-1.o ex16-2.o ex16-3.o ex16-4.o work.o ex16-6.o ex17-1.o ex17-2.o ex17-3.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Day11.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ex16-1.o: ex16-1.c
	$(CC) -c ex16-1.c -o ex16-1.o $(CFLAGS)

ex16-2.o: ex16-2.c
	$(CC) -c ex16-2.c -o ex16-2.o $(CFLAGS)

ex16-3.o: ex16-3.c
	$(CC) -c ex16-3.c -o ex16-3.o $(CFLAGS)

ex16-4.o: ex16-4.c
	$(CC) -c ex16-4.c -o ex16-4.o $(CFLAGS)

work.o: work.c
	$(CC) -c work.c -o work.o $(CFLAGS)

ex16-6.o: ex16-6.c
	$(CC) -c ex16-6.c -o ex16-6.o $(CFLAGS)

ex17-1.o: ex17-1.c
	$(CC) -c ex17-1.c -o ex17-1.o $(CFLAGS)

ex17-2.o: ex17-2.c
	$(CC) -c ex17-2.c -o ex17-2.o $(CFLAGS)

ex17-3.o: ex17-3.c
	$(CC) -c ex17-3.c -o ex17-3.o $(CFLAGS)
