# Project: Day13
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ex18-4.o ex18-5.o ex18-6.o ex18-7.o ex18-8.o ex18-9.o ex18-10.o ex19-1.o ex19-2.o ex19-3.o ex19-4.o ex19-5.o ex19-6.o ex19-7.o ex19-8.o sub.o ex19-9.o input.o average.o ex19-10.o
LINKOBJ  = ex18-4.o ex18-5.o ex18-6.o ex18-7.o ex18-8.o ex18-9.o ex18-10.o ex19-1.o ex19-2.o ex19-3.o ex19-4.o ex19-5.o ex19-6.o ex19-7.o ex19-8.o sub.o ex19-9.o input.o average.o ex19-10.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Day13.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ex18-4.o: ex18-4.c
	$(CC) -c ex18-4.c -o ex18-4.o $(CFLAGS)

ex18-5.o: ex18-5.c
	$(CC) -c ex18-5.c -o ex18-5.o $(CFLAGS)

ex18-6.o: ex18-6.c
	$(CC) -c ex18-6.c -o ex18-6.o $(CFLAGS)

ex18-7.o: ex18-7.c
	$(CC) -c ex18-7.c -o ex18-7.o $(CFLAGS)

ex18-8.o: ex18-8.c
	$(CC) -c ex18-8.c -o ex18-8.o $(CFLAGS)

ex18-9.o: ex18-9.c
	$(CC) -c ex18-9.c -o ex18-9.o $(CFLAGS)

ex18-10.o: ex18-10.c
	$(CC) -c ex18-10.c -o ex18-10.o $(CFLAGS)

ex19-1.o: ex19-1.c
	$(CC) -c ex19-1.c -o ex19-1.o $(CFLAGS)

ex19-2.o: ex19-2.c
	$(CC) -c ex19-2.c -o ex19-2.o $(CFLAGS)

ex19-3.o: ex19-3.c
	$(CC) -c ex19-3.c -o ex19-3.o $(CFLAGS)

ex19-4.o: ex19-4.c
	$(CC) -c ex19-4.c -o ex19-4.o $(CFLAGS)

ex19-5.o: ex19-5.c
	$(CC) -c ex19-5.c -o ex19-5.o $(CFLAGS)

ex19-6.o: ex19-6.c
	$(CC) -c ex19-6.c -o ex19-6.o $(CFLAGS)

ex19-7.o: ex19-7.c
	$(CC) -c ex19-7.c -o ex19-7.o $(CFLAGS)

ex19-8.o: ex19-8.c
	$(CC) -c ex19-8.c -o ex19-8.o $(CFLAGS)

sub.o: sub.c
	$(CC) -c sub.c -o sub.o $(CFLAGS)

ex19-9.o: ex19-9.c
	$(CC) -c ex19-9.c -o ex19-9.o $(CFLAGS)

input.o: input.c
	$(CC) -c input.c -o input.o $(CFLAGS)

average.o: average.c
	$(CC) -c average.c -o average.o $(CFLAGS)

ex19-10.o: ex19-10.c
	$(CC) -c ex19-10.c -o ex19-10.o $(CFLAGS)
