# Project: Day8
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ex12-1.o test.o ex12-2.o ex12-3.o ex12-4.o ex12-5.o ex12-6.o ex12-7.o ex12-8.o ex12-9.o ex12-10.o ex12-11.o ex12-12.o ex12-13.o ex13-1.o ex13-2.o ex13-3.o ex13-4.o ex13-5.o
LINKOBJ  = ex12-1.o test.o ex12-2.o ex12-3.o ex12-4.o ex12-5.o ex12-6.o ex12-7.o ex12-8.o ex12-9.o ex12-10.o ex12-11.o ex12-12.o ex12-13.o ex13-1.o ex13-2.o ex13-3.o ex13-4.o ex13-5.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Day8.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

ex12-1.o: ex12-1.c
	$(CC) -c ex12-1.c -o ex12-1.o $(CFLAGS)

test.o: test.c
	$(CC) -c test.c -o test.o $(CFLAGS)

ex12-2.o: ex12-2.c
	$(CC) -c ex12-2.c -o ex12-2.o $(CFLAGS)

ex12-3.o: ex12-3.c
	$(CC) -c ex12-3.c -o ex12-3.o $(CFLAGS)

ex12-4.o: ex12-4.c
	$(CC) -c ex12-4.c -o ex12-4.o $(CFLAGS)

ex12-5.o: ex12-5.c
	$(CC) -c ex12-5.c -o ex12-5.o $(CFLAGS)

ex12-6.o: ex12-6.c
	$(CC) -c ex12-6.c -o ex12-6.o $(CFLAGS)

ex12-7.o: ex12-7.c
	$(CC) -c ex12-7.c -o ex12-7.o $(CFLAGS)

ex12-8.o: ex12-8.c
	$(CC) -c ex12-8.c -o ex12-8.o $(CFLAGS)

ex12-9.o: ex12-9.c
	$(CC) -c ex12-9.c -o ex12-9.o $(CFLAGS)

ex12-10.o: ex12-10.c
	$(CC) -c ex12-10.c -o ex12-10.o $(CFLAGS)

ex12-11.o: ex12-11.c
	$(CC) -c ex12-11.c -o ex12-11.o $(CFLAGS)

ex12-12.o: ex12-12.c
	$(CC) -c ex12-12.c -o ex12-12.o $(CFLAGS)

ex12-13.o: ex12-13.c
	$(CC) -c ex12-13.c -o ex12-13.o $(CFLAGS)

ex13-1.o: ex13-1.c
	$(CC) -c ex13-1.c -o ex13-1.o $(CFLAGS)

ex13-2.o: ex13-2.c
	$(CC) -c ex13-2.c -o ex13-2.o $(CFLAGS)

ex13-3.o: ex13-3.c
	$(CC) -c ex13-3.c -o ex13-3.o $(CFLAGS)

ex13-4.o: ex13-4.c
	$(CC) -c ex13-4.c -o ex13-4.o $(CFLAGS)

ex13-5.o: ex13-5.c
	$(CC) -c ex13-5.c -o ex13-5.o $(CFLAGS)
