# Project: Day1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = test.o test2.o ex2-4.o ex2-5.o ex2-7.o test3.o ex3-1.o ex3-2.o
LINKOBJ  = test.o test2.o ex2-4.o ex2-5.o ex2-7.o test3.o ex3-1.o ex3-2.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Day1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

test.o: test.c
	$(CC) -c test.c -o test.o $(CFLAGS)

test2.o: test2.c
	$(CC) -c test2.c -o test2.o $(CFLAGS)

ex2-4.o: ex2-4.c
	$(CC) -c ex2-4.c -o ex2-4.o $(CFLAGS)

ex2-5.o: ex2-5.c
	$(CC) -c ex2-5.c -o ex2-5.o $(CFLAGS)

ex2-7.o: ex2-7.c
	$(CC) -c ex2-7.c -o ex2-7.o $(CFLAGS)

test3.o: test3.c
	$(CC) -c test3.c -o test3.o $(CFLAGS)

ex3-1.o: ex3-1.c
	$(CC) -c ex3-1.c -o ex3-1.o $(CFLAGS)

ex3-2.o: ex3-2.c
	$(CC) -c ex3-2.c -o ex3-2.o $(CFLAGS)
